--05. Online Store Database
CREATE TABLE Customers
(
	CustomerID INT NOT NULL IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	Birthday DATE NOT NULL,
	CityID INT NOT NULL 
)

CREATE TABLE Cities
(
	CityID INT NOT NULL IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL
)

CREATE TABLE Orders
(
	OrderID INT NOT NULL IDENTITY PRIMARY KEY,
	CustomerID INT NOT NULL
)

CREATE TABLE ItemTypes
(
	ItemTypeID INT NOT NULL IDENTITY PRIMARY KEY,
	[Name] NVARCHAR (100) NOT NULL
)

CREATE TABLE Items
(
	ItemID INT NOT NULL IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
	ItemTypeID INT NOT NULL
)

CREATE TABLE OrderItems
(
	OrderID INT NOT NULL,
	ItemID INT NOT NULL
	PRIMARY KEY(OrderID, ItemID)
)

ALTER TABLE Customers
ADD FOREIGN KEY(CityID) REFERENCES Cities(CityID) 

ALTER TABLE Orders 
ADD FOREIGN KEY(CustomerID) REFERENCES Customers(CustomerID)

ALTER TABLE OrderItems
ADD FOREIGN KEY(OrderID) REFERENCES Orders(OrderID)

ALTER TABLE OrderItems
ADD FOREIGN KEY(ItemID) REFERENCES Items(ItemID)

ALTER TABLE Items
ADD FOREIGN KEY(ItemTypeID) REFERENCES ItemTypes(ItemTypeID)

--06. University Database
CREATE TABLE Majors
(
	MajorID INT NOT NULL IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL
)

CREATE TABLE Students
(
	StudentID INT NOT NULL IDENTITY PRIMARY KEY,
	StudentNumber INT NOT NULL,
	StudentName NVARCHAR(100) NOT NULL,
	MajorID INT NOT NULL FOREIGN KEY REFERENCES Majors(MajorID)
)

CREATE TABLE Subjects
(
	SubjectID INT NOT NULL IDENTITY PRIMARY KEY,
	SubjectName NVARCHAR(100) NOT NULL
)

CREATE TABLE Agenda
(
	StudentID INT NOT NULL FOREIGN KEY REFERENCES Students(StudentID),
	SubjectID INT NOT NULL FOREIGN KEY REFERENCES Subjects(SubjectID),
	PRIMARY KEY(StudentID, SubjectID)
)

CREATE TABLE Payments
(
	PaymentsID INT NOT NULL IDENTITY PRIMARY KEY,
	PaymentDate DATE NOT NULL,
	PaymentAmount MONEY,
	StudentID INT NOT NULL FOREIGN KEY REFERENCES Students(StudentID)
)